#! /usr/bin/env python3

import os
import re
import requests

s = requests.Session()

BASE_URL = "https://www.vodafone.de"
KABEL_BASE_URL = "https://kabel.vodafone.de"

r = s.get(BASE_URL)

login_payload = {
    "username": os.environ['VODAFONE_USERNAME'],
    "password": os.environ['VODAFONE_PASSWORD'],
    "context":	"vkd",
    "errorURL": "https://www.vodafone.de/meinvodafone/account/login",
    "targetURL": "https://kabel.vodafone.de/"
}

r = s.post(f'{BASE_URL}/mint/session/loginServlet', data = login_payload)

print(r)

r = s.get(f'{KABEL_BASE_URL}/meinkabel/rechnungen/rechnung')

print(r)

p = re.compile(r'/meinkabel/rechnungen/rechnung_download/([a-zA-Z0-9_]*)')

ids = p.findall(r.text)
print(ids)
id = ids[0]

url = f'{KABEL_BASE_URL}/meinkabel/rechnungen/rechnung_download/{id}'
print(url)
r = s.get(url)

import time
ym = time.strftime("%Y-%m")

file_name = f'vodafone-{ym}.pdf'

with open(file_name, 'wb') as f:
    f.write(r.content)

import smtplib
from os.path import basename
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import COMMASPACE, formatdate

def send_mail(send_from, send_to, subject, text, files=None, server="127.0.0.1"):
    assert isinstance(send_to, list)

    msg = MIMEMultipart()
    msg['From'] = send_from
    msg['To'] = COMMASPACE.join(send_to)
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = subject

    msg.attach(MIMEText(text))

    for f in files or []:
        with open(f, "rb") as fil:
            part = MIMEApplication(
                fil.read(),
                Name=basename(f)
            )
        # After the file is closed
        part['Content-Disposition'] = 'attachment; filename="%s"' % basename(f)
        msg.attach(part)


    smtp = smtplib.SMTP(server)
    smtp.login(os.environ['SMTP_USERNAME'], os.environ['SMTP_PASSWORD'])
    smtp.sendmail(send_from, send_to, msg.as_string())
    smtp.close()

send_mail("vodafone-api@leonard.io", ["mail@leonard.io"], f"Monatliche Vodafone-Rechnung {ym}", f"Rechnung {ym}", files = [file_name], server = "in-v3.mailjet.com")
