name: Download invoice every month
on:
  schedule:
    - cron: "0 7 8 * *"
  push:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download invoice and send email
        run: ./vodafone-kabel-email-invoice
        env:
          VODAFONE_USERNAME: ${{ secrets.VODAFONE_USERNAME }}
          VODAFONE_PASSWORD: ${{ secrets.VODAFONE_PASSWORD }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

